# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 15.5.1
      uses: actions/setup-node@v4
      with:
        node-version: 15.5.1
        cache: 'npm'
    - run: npm install
    - run: npm run lint
    - run: npm run prettier
    - run: CI=true npm run test
    - run: npm run build --if-present
